words:
  - compat
  - esbuild
  - nodenext
  - reekystive
  - Vitest
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - pnpm-lock.yaml
  - node_modules
